### ISSUE TITLE
Run further test protocols

### ISSUE THREAD

**Issue by MichaelClerx** [ModellingWebLab/weblab-fc#23]
(Jonathan says:)

Basically here we want to add features iteratively, using existing protocols to test they're working as much as possible. I've tried to suggest a sensible ordering below. These list the protocol used; the actual Python tests using them may be named differently... Note also that some were only run in C++ tests; see https://chaste.cs.ox.ac.uk/trac/browser/chaste/projects/FunctionalCuration/test

- [x] GraphState includes simple units definitions, `independent var units ...`, `output ...` (including for the state vector), and `output ... units ...` #22 
- [x] test_while_loop adds `input ...` and overriding an existing equation #30 
- [x] test_sim_environments checks creation/overriding of input variables and replacing an equation #95
- [x] test_clamping1 adds `clamp ...`; test_clamping2 adds `clamp ... to ...` #96
    - [x] test_clamping3 adds the `units_of` construct (could be done later) #106
- [x] test_mathml_evaluation includes `output ... units ...` (including for variables created by the protocol), `input ... units ... = ...`, `define ... = ...`, and tests correct handling of (most of) the mathematics it's possible to define in a protocol #97
- [x] test_INa_IV_curves has some more complex units definitions, `optional ...`, `var ... units ... = ...`, and `convert ... to ... by ...`; similarly for TestICalProto.py #99
- [x] test_other_ontologies has terms not in `oxmeta` and a generic vector output (not the state vector) - should be covered by #95 and #97 actually - but doesn't seem to pass without further changes, so made ticket: #141
- [x] test_S1S2 checks import handling and redefining the stimulus current #106
- [x] test_nested_protocol makes sure the model interface from a nested protocol is handled correctly, and also includes `define diff(...) = ...` #107
    - [x] The _block protocols test merging model interface sections between parent & nested protocols, where both have parts of the interface defined #107
- [x] test_original_definition checks `original_definition` #108
- [ ] test_model_interpolation has several tests of the `interpolate()` special function #109

**Comment by MichaelClerx** [comment]
Only #109 left now, so might as well close this ticket as a duplicate of that one :D
